spring.application.name=develop

spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.username=admin
spring.datasource.password=secret

server.port = 8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23litQq0HC8j1TfV8o
spring.security.oauth2.client.registration.github.client-secret=36c802e02f762be45b4e9891cab94e1cf0f7f386
spring.security.oauth2.client.registration.github.scope=read:user,user:email,repo,read:org

# GitHub provider endpoints
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=login

app.frontend-url=http://localhost:5173
app.jwt.secret=gGbZh9u7FjXoUYxn4uCejyoJ2UF1Ga8v8IU8lbyuIa8=
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000

app.cookie.secure=true